VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "clsHosComConstants"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Attribute VB_Ext_KEY = "SavedWithClassBuilder6" ,"Yes"
Attribute VB_Ext_KEY = "Top_Level" ,"Yes"
'Option Explicit
'
'Public LINE_DIV         As String
'Public COL_DIV          As String
''Public HOSPT_GB         As String   '병원구분
''Public ResultReviewFlag As String
'
'Private Sub Class_Initialize()
'
'    LINE_DIV = Chr(17)
'    COL_DIV = Chr(19)
''    HOSPT_GB = "10"
'
''    ResultReviewFlag = "5"  '0-임상/해부/혈액, 1-임상, 2-해부, 3-임상/해부, _
'                             4-혈액, 5-임상/혈액, 6-해부/혈액
'End Sub
