VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "clsTables"
Attribute VB_GlobalNameSpace = True
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Attribute VB_Ext_KEY = "SavedWithClassBuilder6" ,"Yes"
Attribute VB_Ext_KEY = "Top_Level" ,"Yes"
Option Explicit

Public Property Let T_LAB904(ByVal vData As String)
    mT_LAB904 = vData
End Property

Public Property Get T_LAB904() As String

    T_LAB904 = mT_LAB904
End Property

Public Property Let T_LAB903(ByVal vData As String)
    mT_LAB903 = vData
End Property

Public Property Get T_LAB903() As String
    T_LAB903 = mT_LAB903
End Property

Public Property Let T_LAB902(ByVal vData As String)
    mT_LAB902 = vData
End Property

Public Property Get T_LAB902() As String
    T_LAB902 = mT_LAB902
End Property

Public Property Let T_LAB901(ByVal vData As String)
    mT_LAB901 = vData
End Property

Public Property Get T_LAB901() As String
    T_LAB901 = mT_LAB901
End Property

Public Property Let T_LAB801(ByVal vData As String)
    mT_LAB801 = vData
End Property

Public Property Get T_LAB801() As String
    T_LAB801 = mT_LAB801
End Property

Public Property Let T_BBS903(ByVal vData As String)
    mT_BBS903 = vData
End Property

Public Property Get T_BBS903() As String
    T_BBS903 = mT_BBS903
End Property

Public Property Let T_COM101(ByVal vData As String)
   mT_COM101 = vData
End Property

Public Property Get T_COM101() As String
    T_COM101 = mT_COM101
End Property

Public Property Let T_BBS902(ByVal vData As String)
    mT_BBS902 = vData
End Property

Public Property Get T_BBS902() As String
    T_BBS902 = mT_BBS902
End Property

Public Property Let T_BBS901(ByVal vData As String)
    mT_BBS901 = vData
End Property

Public Property Get T_BBS901() As String
    T_BBS901 = mT_BBS901
End Property

Public Property Let T_BBS607(ByVal vData As String)
    mT_BBS607 = vData
End Property

Public Property Get T_BBS607() As String
    T_BBS607 = mT_BBS607
End Property

Public Property Let T_BBS606(ByVal vData As String)
    mT_BBS606 = vData
End Property

Public Property Get T_BBS606() As String
    T_BBS606 = mT_BBS606
End Property

Public Property Let T_BBS605(ByVal vData As String)
    mT_BBS605 = vData
End Property

Public Property Get T_BBS605() As String
    T_BBS605 = mT_BBS605
End Property

Public Property Let T_BBS604(ByVal vData As String)
    mT_BBS604 = vData
End Property

Public Property Get T_BBS604() As String
    T_BBS604 = mT_BBS604
End Property

Public Property Let T_BBS603(ByVal vData As String)
    mT_BBS603 = vData
End Property

Public Property Get T_BBS603() As String
    T_BBS603 = mT_BBS603
End Property

Public Property Let T_BBS602(ByVal vData As String)
    mT_BBS602 = vData
End Property

Public Property Get T_BBS602() As String
    T_BBS602 = mT_BBS602
End Property

Public Property Let T_BBS601(ByVal vData As String)
    mT_BBS601 = vData
End Property

Public Property Get T_BBS601() As String
    T_BBS601 = mT_BBS601
End Property

Public Property Let T_BBS506(ByVal vData As String)
    mT_BBS506 = vData
End Property

Public Property Get T_BBS506() As String
    T_BBS506 = mT_BBS506
End Property
Public Property Let T_BBS505(ByVal vData As String)
    mT_BBS505 = vData
End Property

Public Property Get T_BBS505() As String
    T_BBS505 = mT_BBS505
End Property

Public Property Let T_BBS504(ByVal vData As String)
    mT_BBS504 = vData
End Property

Public Property Get T_BBS504() As String
    T_BBS504 = mT_BBS504
End Property

Public Property Let T_BBS503(ByVal vData As String)
    mT_BBS503 = vData
End Property

Public Property Get T_BBS503() As String
    T_BBS503 = mT_BBS503
End Property

Public Property Let T_BBS502(ByVal vData As String)
    mT_BBS502 = vData
End Property

Public Property Get T_BBS502() As String
    T_BBS502 = mT_BBS502
End Property

Public Property Let T_BBS501(ByVal vData As String)
    mT_BBS501 = vData
End Property

Public Property Get T_BBS501() As String
    T_BBS501 = mT_BBS501
End Property

Public Property Let T_BBS414(ByVal vData As String)
    mT_BBS414 = vData
End Property

Public Property Get T_BBS414() As String
    T_BBS414 = mT_BBS414
End Property

Public Property Let T_BBS413(ByVal vData As String)
    mT_BBS413 = vData
End Property

Public Property Get T_BBS413() As String
    T_BBS413 = mT_BBS413
End Property

Public Property Let T_BBS412(ByVal vData As String)
    mT_BBS412 = vData
End Property

Public Property Get T_BBS412() As String
    T_BBS412 = mT_BBS412
End Property

Public Property Let T_BBS411(ByVal vData As String)
    mT_BBS411 = vData
End Property

Public Property Get T_BBS411() As String
    T_BBS411 = mT_BBS411
End Property

Public Property Let T_BBS409(ByVal vData As String)
    mT_BBS409 = vData
End Property

Public Property Get T_BBS409() As String
    T_BBS409 = mT_BBS409
End Property

Public Property Let T_BBS405(ByVal vData As String)
    mT_BBS405 = vData
End Property

Public Property Get T_BBS405() As String
    T_BBS405 = mT_BBS405
End Property

Public Property Let T_BBS404(ByVal vData As String)
    mT_BBS404 = vData
End Property

Public Property Get T_BBS404() As String
    T_BBS404 = mT_BBS404
End Property

Public Property Let T_BBS403(ByVal vData As String)
    mT_BBS403 = vData
End Property

Public Property Get T_BBS403() As String
    T_BBS403 = mT_BBS403
End Property

Public Property Let T_BBS402(ByVal vData As String)
    mT_BBS402 = vData
End Property

Public Property Get T_BBS402() As String
    T_BBS402 = mT_BBS402
End Property

Public Property Let T_BBS401(ByVal vData As String)
    mT_BBS401 = vData
End Property

Public Property Get T_BBS401() As String
    T_BBS401 = mT_BBS401
End Property

Public Property Let T_BBS303(ByVal vData As String)
    mT_BBS303 = vData
End Property

Public Property Get T_BBS303() As String
    T_BBS303 = mT_BBS303
End Property

Public Property Let T_BBS304(ByVal vData As String)
    mT_BBS304 = vData
End Property

Public Property Get T_BBS304() As String
    T_BBS304 = mT_BBS304
End Property

Public Property Let T_BBS302(ByVal vData As String)
    mT_BBS302 = vData
End Property

Public Property Get T_BBS302() As String
    T_BBS302 = mT_BBS302
End Property

Public Property Let T_BBS206(ByVal vData As String)
    mT_BBS206 = vData
End Property

Public Property Get T_BBS206() As String
    T_BBS206 = mT_BBS206
End Property

Public Property Let T_BBS207(ByVal vData As String)
    mT_BBS207 = vData
End Property

Public Property Get T_BBS207() As String
    T_BBS207 = mT_BBS207
End Property

Public Property Let T_BBS203(ByVal vData As String)
    mT_BBS203 = vData
End Property

Public Property Get T_BBS203() As String
    T_BBS203 = mT_BBS203
End Property

Public Property Let T_BBS204(ByVal vData As String)
    mT_BBS204 = vData
End Property

Public Property Get T_BBS204() As String
    T_BBS204 = mT_BBS204
End Property

Public Property Let T_BBS202(ByVal vData As String)
    mT_BBS202 = vData
End Property

Public Property Get T_BBS202() As String
    T_BBS202 = mT_BBS202
End Property

Public Property Let T_BBS201(ByVal vData As String)
    mT_BBS201 = vData
End Property

Public Property Get T_BBS201() As String
    T_BBS201 = mT_BBS201
End Property

Public Property Let T_BBS103(ByVal vData As String)
    mT_BBS103 = vData
End Property

Public Property Get T_BBS103() As String
    T_BBS103 = mT_BBS103
End Property

Public Property Let T_BBS102(ByVal vData As String)
    mT_BBS102 = vData
End Property

Public Property Get T_BBS102() As String
    T_BBS102 = mT_BBS102
End Property

Public Property Let T_BBS101(ByVal vData As String)
    mT_BBS101 = vData
End Property

Public Property Get T_BBS101() As String
    T_BBS101 = mT_BBS101
End Property

Public Property Let T_BBS010(ByVal vData As String)
    mT_BBS010 = vData
End Property

Public Property Get T_BBS010() As String
    T_BBS010 = mT_BBS010
End Property

Public Property Let T_BBS009(ByVal vData As String)
    mT_BBS009 = vData
End Property

Public Property Get T_BBS009() As String
    T_BBS009 = mT_BBS009
End Property

Public Property Let T_BBS008(ByVal vData As String)
    mT_BBS008 = vData
End Property

Public Property Get T_BBS008() As String
    T_BBS008 = mT_BBS008
End Property

Public Property Let T_BBS007(ByVal vData As String)
    mT_BBS007 = vData
End Property

Public Property Get T_BBS007() As String
    T_BBS007 = mT_BBS007
End Property

Public Property Let T_BBS006(ByVal vData As String)
    mT_BBS006 = vData
End Property

Public Property Get T_BBS006() As String
    T_BBS006 = mT_BBS006
End Property

Public Property Let T_BBS004(ByVal vData As String)
    mT_BBS004 = vData
End Property

Public Property Get T_BBS004() As String
    T_BBS004 = mT_BBS004
End Property

Public Property Let T_BBS005(ByVal vData As String)
    mT_BBS005 = vData
End Property

Public Property Get T_BBS005() As String
    T_BBS005 = mT_BBS005
End Property

Public Property Let T_BBS003(ByVal vData As String)
    mT_BBS003 = vData
End Property

Public Property Get T_BBS003() As String
    T_BBS003 = mT_BBS003
End Property

Public Property Let T_BBS002(ByVal vData As String)
    mT_BBS002 = vData
End Property

Public Property Get T_BBS002() As String
    T_BBS002 = mT_BBS002
End Property

Public Property Let T_BBS001(ByVal vData As String)
    mT_BBS001 = vData
End Property

Public Property Get T_BBS001() As String
    T_BBS001 = mT_BBS001
End Property

'Public Property Let T_APS901(ByVal vData As String)
'    mT_APS901 = vData
'End Property
'
'Public Property Get T_APS901() As String
'    T_APS901 = mT_APS901
'End Property
'
'Public Property Let T_APS403(ByVal vData As String)
'    mT_APS403 = vData
'End Property
'
'Public Property Get T_APS403() As String
'    T_APS403 = mT_APS403
'End Property
'
'Public Property Let T_APS402(ByVal vData As String)
'    mT_APS402 = vData
'End Property
'
'Public Property Get T_APS402() As String
'    T_APS402 = mT_APS402
'End Property
'
'Public Property Let T_APS401(ByVal vData As String)
'    mT_APS401 = vData
'End Property
'
'Public Property Get T_APS401() As String
'    T_APS401 = mT_APS401
'End Property
'
'Public Property Let T_APS321(ByVal vData As String)
'    mT_APS321 = vData
'End Property
'
'Public Property Get T_APS321() As String
'    T_APS321 = mT_APS321
'End Property
'
'Public Property Let T_APS320(ByVal vData As String)
'    mT_APS320 = vData
'End Property
'
'Public Property Get T_APS320() As String
'    T_APS320 = mT_APS320
'End Property
'
'Public Property Let T_APS319(ByVal vData As String)
'    mT_APS319 = vData
'End Property
'
'Public Property Get T_APS319() As String
'    T_APS319 = mT_APS319
'End Property
'
'Public Property Let T_APS318(ByVal vData As String)
'    mT_APS318 = vData
'End Property
'
'Public Property Get T_APS318() As String
'    T_APS318 = mT_APS318
'End Property
'
'Public Property Let T_APS317(ByVal vData As String)
'    mT_APS317 = vData
'End Property
'
'Public Property Get T_APS317() As String
'    T_APS317 = mT_APS317
'End Property
'
'Public Property Let T_APS313(ByVal vData As String)
'    mT_APS313 = vData
'End Property
'
'Public Property Get T_APS313() As String
'    T_APS313 = mT_APS313
'End Property
'
'Public Property Let T_APS312(ByVal vData As String)
'    mT_APS312 = vData
'End Property
'
'Public Property Get T_APS312() As String
'    T_APS312 = mT_APS312
'End Property
'
'Public Property Let T_APS311(ByVal vData As String)
'    mT_APS311 = vData
'End Property
'
'Public Property Get T_APS311() As String
'    T_APS311 = mT_APS311
'End Property
'
'Public Property Let T_APS310(ByVal vData As String)
'    mT_APS310 = vData
'End Property
'
'Public Property Get T_APS310() As String
'    T_APS310 = mT_APS310
'End Property
'
'Public Property Let T_APS309(ByVal vData As String)
'    mT_APS309 = vData
'End Property
'
'Public Property Get T_APS309() As String
'    T_APS309 = mT_APS309
'End Property
'
'Public Property Let T_APS308(ByVal vData As String)
'    mT_APS308 = vData
'End Property
'
'Public Property Get T_APS308() As String
'    T_APS308 = mT_APS308
'End Property
'
'Public Property Let T_APS307(ByVal vData As String)
'    mT_APS307 = vData
'End Property
'
'Public Property Get T_APS307() As String
'    T_APS307 = mT_APS307
'End Property
'
'Public Property Let T_APS306(ByVal vData As String)
'    mT_APS306 = vData
'End Property
'
'Public Property Get T_APS306() As String
'    T_APS306 = mT_APS306
'End Property
'
'Public Property Let T_APS305(ByVal vData As String)
'    mT_APS305 = vData
'End Property
'
'Public Property Get T_APS305() As String
'    T_APS305 = mT_APS305
'End Property
'
'Public Property Let T_APS304(ByVal vData As String)
'    mT_APS304 = vData
'End Property
'
'Public Property Get T_APS304() As String
'    T_APS304 = mT_APS304
'End Property
'
'Public Property Let T_APS303(ByVal vData As String)
'    mT_APS303 = vData
'End Property
'
'Public Property Get T_APS303() As String
'    T_APS303 = mT_APS303
'End Property
'
'Public Property Let T_APS302(ByVal vData As String)
'    mT_APS302 = vData
'End Property
'
'Public Property Get T_APS302() As String
'    T_APS302 = mT_APS302
'End Property
'
'Public Property Let T_APS301(ByVal vData As String)
'    mT_APS301 = vData
'End Property
'
'Public Property Get T_APS301() As String
'    T_APS301 = mT_APS301
'End Property
'
'Public Property Let T_APS207(ByVal vData As String)
'    mT_APS207 = vData
'End Property
'
'Public Property Get T_APS207() As String
'    T_APS207 = mT_APS207
'End Property
'
'Public Property Let T_APS206(ByVal vData As String)
'    mT_APS206 = vData
'End Property
'
'Public Property Get T_APS206() As String
'    T_APS206 = mT_APS206
'End Property
'
'Public Property Let T_APS205(ByVal vData As String)
'    mT_APS205 = vData
'End Property
'
'Public Property Get T_APS205() As String
'    T_APS205 = mT_APS205
'End Property
'
'Public Property Let T_APS204(ByVal vData As String)
'
'' X.T_APS204 = 5
'    mT_APS204 = vData
'End Property
'
'
'Public Property Get T_APS204() As String
'
'' X.T_APS204
'    T_APS204 = mT_APS204
'End Property
'
'
'
'Public Property Let T_APS203(ByVal vData As String)
'
'' X.T_APS203 = 5
'    mT_APS203 = vData
'End Property
'
'
'Public Property Get T_APS203() As String
'
'' X.T_APS203
'    T_APS203 = mT_APS203
'End Property
'
'
'
'Public Property Let T_APS202(ByVal vData As String)
'
'' X.T_APS202 = 5
'    mT_APS202 = vData
'End Property
'
'
'Public Property Get T_APS202() As String
'
'' X.T_APS202
'    T_APS202 = mT_APS202
'End Property
'
'
'
'Public Property Let T_APS201(ByVal vData As String)
'
'' X.T_APS201 = 5
'    mT_APS201 = vData
'End Property
'
'
'Public Property Get T_APS201() As String
'
'' X.T_APS201
'    T_APS201 = mT_APS201
'End Property
'
'
'
'Public Property Let T_APS106(ByVal vData As String)
'
'' X.T_APS106 = 5
'    mT_APS106 = vData
'End Property
'
'
'Public Property Get T_APS106() As String
'
'' X.T_APS106
'    T_APS106 = mT_APS106
'End Property
'
'
'
'Public Property Let T_APS105(ByVal vData As String)
'
'' X.T_APS105 = 5
'    mT_APS105 = vData
'End Property
'
'
'Public Property Get T_APS105() As String
'
'' X.T_APS105
'    T_APS105 = mT_APS105
'End Property
'
'
'
'Public Property Let T_APS104(ByVal vData As String)
'
'' X.T_APS104 = 5
'    mT_APS104 = vData
'End Property
'
'
'Public Property Get T_APS104() As String
'
'' X.T_APS104
'    T_APS104 = mT_APS104
'End Property
'
'
'
'Public Property Let T_APS103(ByVal vData As String)
'
'' X.T_APS103 = 5
'    mT_APS103 = vData
'End Property
'
'
'Public Property Get T_APS103() As String
'
'' X.T_APS103
'    T_APS103 = mT_APS103
'End Property
'
'
'
'Public Property Let T_APS102(ByVal vData As String)
'
'' X.T_APS102 = 5
'    mT_APS102 = vData
'End Property
'
'
'Public Property Get T_APS102() As String
'
'' X.T_APS102
'    T_APS102 = mT_APS102
'End Property
'
'
'
'Public Property Let T_APS101(ByVal vData As String)
'
'' X.T_APS101 = 5
'    mT_APS101 = vData
'End Property
'
'
'Public Property Get T_APS101() As String
'
'' X.T_APS101
'    T_APS101 = mT_APS101
'End Property
'
'
'
'Public Property Let T_APS011(ByVal vData As String)
'
'' X.T_APS011 = 5
'    mT_APS011 = vData
'End Property
'
'
'Public Property Get T_APS011() As String
'
'' X.T_APS011
'    T_APS011 = mT_APS011
'End Property
'
'
'
'Public Property Let T_APS009(ByVal vData As String)
'
'' X.T_APS009 = 5
'    mT_APS009 = vData
'End Property
'
'
'Public Property Get T_APS009() As String
'
'' X.T_APS009
'    T_APS009 = mT_APS009
'End Property
'
'
'
'Public Property Let T_APS008(ByVal vData As String)
'
'' X.T_APS008 = 5
'    mT_APS008 = vData
'End Property
'
'
'Public Property Get T_APS008() As String
'
'' X.T_APS008
'    T_APS008 = mT_APS008
'End Property
'
'
'
'Public Property Let T_APS007(ByVal vData As String)
'
'' X.T_APS007 = 5
'    mT_APS007 = vData
'End Property
'
'
'Public Property Get T_APS007() As String
'
'' X.T_APS007
'    T_APS007 = mT_APS007
'End Property
'
'
'
'Public Property Let T_APS006(ByVal vData As String)
'
'' X.T_APS006 = 5
'    mT_APS006 = vData
'End Property
'
'
'Public Property Get T_APS006() As String
'
'' X.T_APS006
'    T_APS006 = mT_APS006
'End Property
'
'
'
'Public Property Let T_APS005(ByVal vData As String)
'
'' X.T_APS005 = 5
'    mT_APS005 = vData
'End Property
'
'
'Public Property Get T_APS005() As String
'
'' X.T_APS005
'    T_APS005 = mT_APS005
'End Property
'
'
'
'Public Property Let T_APS004(ByVal vData As String)
'
'' X.T_APS004 = 5
'    mT_APS004 = vData
'End Property
'
'
'Public Property Get T_APS004() As String
'
'' X.T_APS004
'    T_APS004 = mT_APS004
'End Property
'
'
'
'Public Property Let T_APS003(ByVal vData As String)
'
'' X.T_APS003 = 5
'    mT_APS003 = vData
'End Property
'
'
'Public Property Get T_APS003() As String
'
'' X.T_APS003
'    T_APS003 = mT_APS003
'End Property
'
'
'
'Public Property Let T_APS002(ByVal vData As String)
'
'' X.T_APS002 = 5
'    mT_APS002 = vData
'End Property
'
'
'Public Property Get T_APS002() As String
'
'' X.T_APS002
'    T_APS002 = mT_APS002
'End Property
'
'
'
'Public Property Let T_APS001(ByVal vData As String)
'
'' X.T_APS001 = 5
'    mT_APS001 = vData
'End Property
'
'
'Public Property Get T_APS001() As String
'
'' X.T_APS001
'    T_APS001 = mT_APS001
'End Property



Public Property Let T_INT003(ByVal vData As String)
    mT_INT003 = vData
End Property

Public Property Get T_INT003() As String
    T_INT003 = mT_INT003
End Property

Public Property Let T_INT002(ByVal vData As String)
    mT_INT002 = vData
End Property

Public Property Get T_INT002() As String
    T_INT002 = mT_INT002
End Property

Public Property Let T_INT001(ByVal vData As String)
    mT_INT001 = vData
End Property

Public Property Get T_INT001() As String
    T_INT001 = mT_INT001
End Property

Public Property Let T_LAB999(ByVal vData As String)
    mT_LAB999 = vData
End Property

Public Property Get T_LAB999() As String
    T_LAB999 = mT_LAB999
End Property

Public Property Let T_LAB704(ByVal vData As String)
    mT_LAB704 = vData
End Property

Public Property Get T_LAB704() As String
    T_LAB704 = mT_LAB704
End Property

Public Property Let T_LAB703(ByVal vData As String)
    mT_LAB703 = vData
End Property

Public Property Get T_LAB703() As String
    T_LAB703 = mT_LAB703
End Property

Public Property Let T_LAB702(ByVal vData As String)
    mT_LAB702 = vData
End Property

Public Property Get T_LAB702() As String
    T_LAB702 = mT_LAB702
End Property

Public Property Let T_LAB701(ByVal vData As String)
    mT_LAB701 = vData
End Property

Public Property Get T_LAB701() As String
    T_LAB701 = mT_LAB701
End Property

Public Property Let T_LAB604(ByVal vData As String)
    mT_LAB604 = vData
End Property

Public Property Get T_LAB604() As String
    T_LAB604 = mT_LAB604
End Property

Public Property Let T_LAB603(ByVal vData As String)
    mT_LAB603 = vData
End Property

Public Property Get T_LAB603() As String
    T_LAB603 = mT_LAB603
End Property

Public Property Let T_LAB602(ByVal vData As String)
    mT_LAB602 = vData
End Property

Public Property Get T_LAB602() As String
    T_LAB602 = mT_LAB602
End Property

Public Property Let T_LAB601(ByVal vData As String)
    mT_LAB601 = vData
End Property

Public Property Get T_LAB601() As String
    T_LAB601 = mT_LAB601
End Property

Public Property Let T_LAB501(ByVal vData As String)
    mT_LAB501 = vData
End Property

Public Property Get T_LAB501() As String
    T_LAB501 = mT_LAB501
End Property

Public Property Let T_LAB502(ByVal vData As String)
    mT_LAB502 = vData
End Property

Public Property Get T_LAB502() As String
    T_LAB502 = mT_LAB502
End Property

Public Property Let T_LAB503(ByVal vData As String)
    mT_LAB503 = vData
End Property

Public Property Get T_LAB503() As String
    T_LAB503 = mT_LAB503
End Property

Public Property Let T_LAB504(ByVal vData As String)
    mT_LAB504 = vData
End Property

Public Property Get T_LAB504() As String
    T_LAB504 = mT_LAB504
End Property

Public Property Let T_LAB505(ByVal vData As String)
    mT_LAB505 = vData
End Property

Public Property Get T_LAB505() As String
    T_LAB505 = mT_LAB505
End Property

Public Property Let T_LAB506(ByVal vData As String)
    mT_LAB506 = vData
End Property

Public Property Get T_LAB506() As String
    T_LAB506 = mT_LAB506
End Property

Public Property Let T_LAB407(ByVal vData As String)
    mT_LAB407 = vData
End Property

Public Property Get T_LAB407() As String
    T_LAB407 = mT_LAB407
End Property

Public Property Let T_LAB406(ByVal vData As String)
    mT_LAB406 = vData
End Property

Public Property Get T_LAB406() As String
    T_LAB406 = mT_LAB406
End Property

Public Property Let T_LAB405(ByVal vData As String)
    mT_LAB405 = vData
End Property

Public Property Get T_LAB405() As String
    T_LAB405 = mT_LAB405
End Property

Public Property Let T_LAB404(ByVal vData As String)
    mT_LAB404 = vData
End Property

Public Property Get T_LAB404() As String
    T_LAB404 = mT_LAB404
End Property

Public Property Let T_LAB403(ByVal vData As String)
    mT_LAB403 = vData
End Property

Public Property Get T_LAB403() As String
    T_LAB403 = mT_LAB403
End Property

Public Property Let T_LAB402(ByVal vData As String)
    mT_LAB402 = vData
End Property

Public Property Get T_LAB402() As String
    T_LAB402 = mT_LAB402
End Property

Public Property Let T_LAB401(ByVal vData As String)
    mT_LAB401 = vData
End Property

Public Property Get T_LAB401() As String
    T_LAB401 = mT_LAB401
End Property

Public Property Let T_LAB361(ByVal vData As String)
    mT_LAB361 = vData
End Property

Public Property Get T_LAB361() As String
    T_LAB361 = mT_LAB361
End Property

Public Property Let T_LAB360(ByVal vData As String)
    mT_LAB360 = vData
End Property

Public Property Get T_LAB360() As String
    T_LAB360 = mT_LAB360
End Property

Public Property Let T_LAB354(ByVal vData As String)
    mT_LAB354 = vData
End Property

Public Property Get T_LAB354() As String
    T_LAB354 = mT_LAB354
End Property

Public Property Let T_LAB353(ByVal vData As String)
    mT_LAB353 = vData
End Property

Public Property Get T_LAB353() As String
    T_LAB353 = mT_LAB353
End Property

Public Property Let T_LAB352(ByVal vData As String)
    mT_LAB352 = vData
End Property

Public Property Get T_LAB352() As String
    T_LAB352 = mT_LAB352
End Property

Public Property Let T_LAB351(ByVal vData As String)
    mT_LAB351 = vData
End Property

Public Property Get T_LAB351() As String
    T_LAB351 = mT_LAB351
End Property

Public Property Let T_LAB350(ByVal vData As String)
    mT_LAB350 = vData
End Property

Public Property Get T_LAB350() As String
    T_LAB350 = mT_LAB350
End Property

Public Property Let T_LAB310(ByVal vData As String)
    mT_LAB310 = vData
End Property

Public Property Get T_LAB310() As String
    T_LAB310 = mT_LAB310
End Property

Public Property Let T_LAB309(ByVal vData As String)
    mT_LAB309 = vData
End Property

Public Property Get T_LAB309() As String
    T_LAB309 = mT_LAB309
End Property

Public Property Let T_LAB308(ByVal vData As String)
    mT_LAB308 = vData
End Property

Public Property Get T_LAB308() As String
    T_LAB308 = mT_LAB308
End Property

Public Property Let T_LAB307(ByVal vData As String)
    mT_LAB307 = vData
End Property

Public Property Get T_LAB307() As String
    T_LAB307 = mT_LAB307
End Property

Public Property Let T_LAB306(ByVal vData As String)
    mT_LAB306 = vData
End Property

Public Property Get T_LAB306() As String
    T_LAB306 = mT_LAB306
End Property

Public Property Let T_LAB305(ByVal vData As String)
    mT_LAB305 = vData
End Property

Public Property Get T_LAB305() As String
    T_LAB305 = mT_LAB305
End Property

Public Property Let T_LAB304(ByVal vData As String)
    mT_LAB304 = vData
End Property

Public Property Get T_LAB304() As String
    T_LAB304 = mT_LAB304
End Property

Public Property Let T_LAB303(ByVal vData As String)
    mT_LAB303 = vData
End Property

Public Property Get T_LAB303() As String
    T_LAB303 = mT_LAB303
End Property

Public Property Let T_LAB302(ByVal vData As String)
    mT_LAB302 = vData
End Property

Public Property Get T_LAB302() As String
    T_LAB302 = mT_LAB302
End Property

Public Property Let T_LAB301(ByVal vData As String)
    mT_LAB301 = vData
End Property

Public Property Get T_LAB301() As String
    T_LAB301 = mT_LAB301
End Property

Public Property Let T_LAB206(ByVal vData As String)
    mT_LAB206 = vData
End Property

Public Property Get T_LAB206() As String
    T_LAB206 = mT_LAB206
End Property

Public Property Let T_LAB205(ByVal vData As String)
    mT_LAB205 = vData
End Property

Public Property Get T_LAB205() As String
    T_LAB205 = mT_LAB205
End Property

Public Property Let T_LAB204(ByVal vData As String)
    mT_LAB204 = vData
End Property

Public Property Get T_LAB204() As String

    T_LAB204 = mT_LAB204
End Property

Public Property Let T_LAB203(ByVal vData As String)
    mT_LAB203 = vData
End Property

Public Property Get T_LAB203() As String
    T_LAB203 = mT_LAB203
End Property

Public Property Let T_LAB202(ByVal vData As String)
    mT_LAB202 = vData
End Property

Public Property Get T_LAB202() As String
    T_LAB202 = mT_LAB202
End Property

Public Property Let T_LAB201(ByVal vData As String)
    mT_LAB201 = vData
End Property

Public Property Get T_LAB201() As String
    T_LAB201 = mT_LAB201
End Property

Public Property Let T_LAB195(ByVal vData As String)
    mT_LAB195 = vData
End Property

Public Property Get T_LAB195() As String
    T_LAB195 = mT_LAB195
End Property

Public Property Let T_LAB106(ByVal vData As String)
    mT_LAB106 = vData
End Property

Public Property Get T_LAB106() As String
    T_LAB106 = mT_LAB106
End Property

Public Property Let T_LAB105(ByVal vData As String)
    mT_LAB105 = vData
End Property

Public Property Get T_LAB105() As String
    T_LAB105 = mT_LAB105
End Property

Public Property Let T_LAB104(ByVal vData As String)
    mT_LAB104 = vData
End Property

Public Property Get T_LAB104() As String
    T_LAB104 = mT_LAB104
End Property

Public Property Let T_LAB103(ByVal vData As String)
    mT_LAB103 = vData
End Property

Public Property Get T_LAB103() As String
    T_LAB103 = mT_LAB103
End Property

Public Property Let T_LAB102(ByVal vData As String)
    mT_LAB102 = vData
End Property

Public Property Get T_LAB102() As String
    T_LAB102 = mT_LAB102
End Property

Public Property Let T_LAB101(ByVal vData As String)
    mT_LAB101 = vData
End Property

Public Property Get T_LAB101() As String
    T_LAB101 = mT_LAB101
End Property

Public Property Let T_LAB099(ByVal vData As String)
    mT_LAB099 = vData
End Property

Public Property Get T_LAB099() As String
    T_LAB099 = mT_LAB099
End Property

Public Property Let T_LAB041(ByVal vData As String)
    mT_LAB041 = vData
End Property

Public Property Get T_LAB041() As String
    T_LAB041 = mT_LAB041
End Property

Public Property Let T_LAB036(ByVal vData As String)
    mT_LAB036 = vData
End Property

Public Property Get T_LAB036() As String
    T_LAB036 = mT_LAB036
End Property

Public Property Let T_LAB035(ByVal vData As String)
    mT_LAB035 = vData
End Property

Public Property Get T_LAB035() As String
    T_LAB035 = mT_LAB035
End Property

Public Property Let T_LAB034(ByVal vData As String)
    mT_LAB034 = vData
End Property

Public Property Get T_LAB034() As String
    T_LAB034 = mT_LAB034
End Property

Public Property Let T_LAB033(ByVal vData As String)
    mT_LAB033 = vData
End Property

Public Property Get T_LAB033() As String
    T_LAB033 = mT_LAB033
End Property

Public Property Let T_LAB032(ByVal vData As String)
    mT_LAB032 = vData
End Property

Public Property Get T_LAB032() As String
    T_LAB032 = mT_LAB032
End Property

Public Property Let T_LAB031(ByVal vData As String)
    mT_LAB031 = vData
End Property

Public Property Get T_LAB031() As String
    T_LAB031 = mT_LAB031
End Property

Public Property Let T_LAB030(ByVal vData As String)
    mT_LAB030 = vData
End Property

Public Property Get T_LAB030() As String
    T_LAB030 = mT_LAB030
End Property

Public Property Let T_LAB029(ByVal vData As String)
    mT_LAB029 = vData
End Property

Public Property Get T_LAB029() As String
    T_LAB029 = mT_LAB029
End Property

Public Property Let T_LAB028(ByVal vData As String)
    mT_LAB028 = vData
End Property

Public Property Get T_LAB028() As String
    T_LAB028 = mT_LAB028
End Property

Public Property Let T_LAB027(ByVal vData As String)
    mT_LAB027 = vData
End Property

Public Property Get T_LAB027() As String
    T_LAB027 = mT_LAB027
End Property

Public Property Let T_LAB026(ByVal vData As String)
    mT_LAB026 = vData
End Property

Public Property Get T_LAB026() As String
    T_LAB026 = mT_LAB026
End Property

Public Property Let T_LAB025(ByVal vData As String)
    mT_LAB025 = vData
End Property

Public Property Get T_LAB025() As String
    T_LAB025 = mT_LAB025
End Property

Public Property Let T_LAB024(ByVal vData As String)
    mT_LAB024 = vData
End Property

Public Property Get T_LAB024() As String
    T_LAB024 = mT_LAB024
End Property

Public Property Let T_LAB023(ByVal vData As String)
    mT_LAB023 = vData
End Property

Public Property Get T_LAB023() As String
    T_LAB023 = mT_LAB023
End Property

Public Property Let T_LAB022(ByVal vData As String)
    mT_LAB022 = vData
End Property

Public Property Get T_LAB022() As String
    T_LAB022 = mT_LAB022
End Property

Public Property Let T_LAB021(ByVal vData As String)
    mT_LAB021 = vData
End Property

Public Property Get T_LAB021() As String
    T_LAB021 = mT_LAB021
End Property

Public Property Let T_LAB015(ByVal vData As String)
    mT_LAB015 = vData
End Property

Public Property Get T_LAB015() As String
    T_LAB015 = mT_LAB015
End Property

Public Property Let T_LAB014(ByVal vData As String)
    mT_LAB014 = vData
End Property

Public Property Get T_LAB014() As String
    T_LAB014 = mT_LAB014
End Property

Public Property Let T_LAB013(ByVal vData As String)
    mT_LAB013 = vData
End Property

Public Property Get T_LAB013() As String
    T_LAB013 = mT_LAB013
End Property

Public Property Let T_LAB012(ByVal vData As String)
    mT_LAB012 = vData
End Property

Public Property Get T_LAB012() As String
    T_LAB012 = mT_LAB012
End Property

Public Property Let T_LAB011(ByVal vData As String)
    mT_LAB011 = vData
End Property

Public Property Get T_LAB011() As String
    T_LAB011 = mT_LAB011
End Property

Public Property Let T_LAB010(ByVal vData As String)
    mT_LAB010 = vData
End Property

Public Property Get T_LAB010() As String
    T_LAB010 = mT_LAB010
End Property

Public Property Let T_LAB009(ByVal vData As String)
    mT_LAB009 = vData
End Property

Public Property Get T_LAB009() As String
    T_LAB009 = mT_LAB009
End Property

Public Property Let T_LAB008(ByVal vData As String)
    mT_LAB008 = vData
End Property

Public Property Get T_LAB008() As String
    T_LAB008 = mT_LAB008
End Property

Public Property Let T_LAB007(ByVal vData As String)
    mT_LAB007 = vData
End Property

Public Property Get T_LAB007() As String
    T_LAB007 = mT_LAB007
End Property

Public Property Let T_LAB006(ByVal vData As String)
    mT_LAB006 = vData
End Property

Public Property Get T_LAB006() As String
    T_LAB006 = mT_LAB006
End Property

Public Property Let T_LAB005(ByVal vData As String)
    mT_LAB005 = vData
End Property

Public Property Get T_LAB005() As String
    T_LAB005 = mT_LAB005
End Property

Public Property Let T_LAB004(ByVal vData As String)
    mT_LAB004 = vData
End Property

Public Property Get T_LAB004() As String
    T_LAB004 = mT_LAB004
End Property

Public Property Let T_LAB003(ByVal vData As String)
    mT_LAB003 = vData
End Property

Public Property Get T_LAB003() As String
    T_LAB003 = mT_LAB003
End Property

Public Property Let T_LAB002(ByVal vData As String)
    mT_LAB002 = vData
End Property

Public Property Get T_LAB002() As String
    T_LAB002 = mT_LAB002
End Property

Public Property Let T_LAB001(ByVal vData As String)
    mT_LAB001 = vData
End Property

Public Property Get T_LAB001() As String
    T_LAB001 = mT_LAB001
End Property

Public Property Let T_HIS010(ByVal vData As String)
    mT_HIS010 = vData
End Property

Public Property Get T_HIS010() As String
    T_HIS010 = mT_HIS010
End Property

Public Property Let T_HIS009(ByVal vData As String)
    mT_HIS009 = vData
End Property

Public Property Get T_HIS009() As String
    T_HIS009 = mT_HIS009
End Property

Public Property Let T_HIS008(ByVal vData As String)
    mT_HIS008 = vData
End Property

Public Property Get T_HIS008() As String
    T_HIS008 = mT_HIS008
End Property

Public Property Let T_HIS007(ByVal vData As String)
    mT_HIS007 = vData
End Property

Public Property Get T_HIS007() As String
    T_HIS007 = mT_HIS007
End Property

Public Property Let T_HIS006(ByVal vData As String)
    mT_HIS006 = vData
End Property

Public Property Get T_HIS006() As String
    T_HIS006 = mT_HIS006
End Property

Public Property Let T_HIS005(ByVal vData As String)
    mT_HIS005 = vData
End Property

Public Property Get T_HIS005() As String
    T_HIS005 = mT_HIS005
End Property

Public Property Let T_HIS004(ByVal vData As String)
    mT_HIS004 = vData
End Property

Public Property Get T_HIS004() As String
    T_HIS004 = mT_HIS004
End Property

Public Property Let T_HIS003(ByVal vData As String)
    mT_HIS003 = vData
End Property

Public Property Get T_HIS003() As String
    T_HIS003 = mT_HIS003
End Property

Public Property Let T_HIS002(ByVal vData As String)
    mT_HIS002 = vData
End Property

Public Property Get T_HIS002() As String
    T_HIS002 = mT_HIS002
End Property

Public Property Let T_HIS001(ByVal vData As String)
    mT_HIS001 = vData
End Property

Public Property Get T_HIS001() As String
    T_HIS001 = mT_HIS001
End Property

Public Property Let T_COM099(ByVal vData As String)
    mT_COM099 = vData
End Property

Public Property Get T_COM099() As String
    T_COM099 = mT_COM099
End Property

Public Property Let T_COM017(ByVal vData As String)
    mT_COM017 = vData
End Property

Public Property Get T_COM017() As String
    T_COM017 = mT_COM017
End Property

Public Property Let T_COM016(ByVal vData As String)
    mT_COM016 = vData
End Property

Public Property Get T_COM016() As String
    T_COM016 = mT_COM016
End Property

Public Property Let T_COM015(ByVal vData As String)
    mT_COM015 = vData
End Property

Public Property Get T_COM015() As String
    T_COM015 = mT_COM015
End Property

Public Property Let T_COM014(ByVal vData As String)
    mT_COM014 = vData
End Property

Public Property Get T_COM014() As String
    T_COM014 = mT_COM014
End Property

Public Property Let T_COM013(ByVal vData As String)
    mT_COM013 = vData
End Property

Public Property Get T_COM013() As String
    T_COM013 = mT_COM013
End Property

Public Property Let T_COM012(ByVal vData As String)
    mT_COM012 = vData
End Property

Public Property Get T_COM012() As String
    T_COM012 = mT_COM012
End Property

Public Property Let T_COM011(ByVal vData As String)
    mT_COM011 = vData
End Property

Public Property Get T_COM011() As String
    T_COM011 = mT_COM011
End Property

Public Property Let T_COM010(ByVal vData As String)
    mT_COM010 = vData
End Property

Public Property Get T_COM010() As String
    T_COM010 = mT_COM010
End Property

Public Property Let T_COM009(ByVal vData As String)
    mT_COM009 = vData
End Property

Public Property Get T_COM009() As String
    T_COM009 = mT_COM009
End Property

Public Property Let T_COM008(ByVal vData As String)
    mT_COM008 = vData
End Property

Public Property Get T_COM008() As String
    T_COM008 = mT_COM008
End Property

Public Property Let T_COM007(ByVal vData As String)
    mT_COM007 = vData
End Property

Public Property Get T_COM007() As String
    T_COM007 = mT_COM007
End Property

Public Property Let T_COM006(ByVal vData As String)
    mT_COM006 = vData
End Property

Public Property Get T_COM006() As String
    T_COM006 = mT_COM006
End Property

Public Property Let T_COM005(ByVal vData As String)
    mT_COM005 = vData
End Property

Public Property Get T_COM005() As String
    T_COM005 = mT_COM005
End Property

Public Property Let T_COM004(ByVal vData As String)
    mT_COM004 = vData
End Property

Public Property Get T_COM004() As String
    T_COM004 = mT_COM004
End Property

Public Property Let T_COM003(ByVal vData As String)
    mT_COM003 = vData
End Property

Public Property Get T_COM003() As String
    T_COM003 = mT_COM003
End Property

Public Property Let T_COM002(ByVal vData As String)
    mT_COM002 = vData
End Property

Public Property Get T_COM002() As String
    T_COM002 = mT_COM002
End Property

Public Property Let T_COM001(ByVal vData As String)
    mT_COM001 = vData
End Property

Public Property Get T_COM001() As String
    T_COM001 = mT_COM001
End Property

Public Property Get T_ICS001() As String
    T_ICS001 = mT_ICS001
End Property

Public Property Let T_ICS001(ByVal vData As String)
    mT_ICS001 = vData
End Property

Public Property Get T_ICS002() As String
    T_ICS002 = mT_ICS002
End Property

Public Property Let T_ICS002(ByVal vData As String)
    mT_ICS002 = vData
End Property

Public Property Get T_ICS101() As String
    T_ICS101 = mT_ICS101
End Property

Public Property Let T_ICS101(ByVal vData As String)
    mT_ICS101 = vData
End Property

Public Property Get T_ICS102() As String
    T_ICS102 = mT_ICS102
End Property

Public Property Let T_ICS102(ByVal vData As String)
    mT_ICS102 = vData
End Property

Public Property Get T_ICS103() As String
    T_ICS103 = mT_ICS103
End Property

Public Property Let T_ICS103(ByVal vData As String)
    mT_ICS103 = vData
End Property

Public Property Get T_ICS201() As String
    T_ICS201 = mT_ICS201
End Property

Public Property Let T_ICS201(ByVal vData As String)
    mT_ICS201 = vData
End Property

Public Property Get T_ICS202() As String
    T_ICS202 = mT_ICS202
End Property

Public Property Let T_ICS202(ByVal vData As String)
    mT_ICS202 = vData
End Property

Public Property Get T_ICS301() As String
    T_ICS301 = mT_ICS301
End Property

Public Property Let T_ICS301(ByVal vData As String)
    mT_ICS301 = vData
End Property

Public Property Get T_ICS302() As String
    T_ICS302 = mT_ICS302
End Property

Public Property Let T_ICS302(ByVal vData As String)
    mT_ICS302 = vData
End Property

Private Sub Class_Initialize()

    If IsSetTable = False Then Call SetTable
    IsSetTable = True
    
End Sub

