INSERT INTO equipexam
  (equipno, equipcode, examcode, examname, resprec, reflow, refhigh, paniclow, panichigh, deltavalue, seqno, examflag, examtype)
VALUES
  ('AU480', '97', 'C3780', 'Na', 0, '', '', '', '', '', 97, 1, 'C');

INSERT INTO equipexam
  (equipno, equipcode, examcode, examname, resprec, reflow, refhigh, paniclow, panichigh, deltavalue, seqno, examflag, examtype)
VALUES
  ('AU480', '02', 'L110902', 'Alb', 1, '', '', '', '', '', 2, 1, 'C');

INSERT INTO equipexam
  (equipno, equipcode, examcode, examname, resprec, reflow, refhigh, paniclow, panichigh, deltavalue, seqno, examflag, examtype)
VALUES
  ('AU480', '98', 'C3711', 'K', 1, '', '', '', '', '', 98, 1, 'C');

INSERT INTO equipexam
  (equipno, equipcode, examcode, examname, resprec, reflow, refhigh, paniclow, panichigh, deltavalue, seqno, examflag, examtype)
VALUES
  ('AU480', '03', 'L11001501', 'GLB', 1, '', '', '', '', '', 3, 1, 'C');

INSERT INTO equipexam
  (equipno, equipcode, examcode, examname, resprec, reflow, refhigh, paniclow, panichigh, deltavalue, seqno, examflag, examtype)
VALUES
  ('AU480', '04', 'L11001502', 'A/G', 1, '', '', '', '', '', 4, 1, 'C');

INSERT INTO equipexam
  (equipno, equipcode, examcode, examname, resprec, reflow, refhigh, paniclow, panichigh, deltavalue, seqno, examflag, examtype)
VALUES
  ('AU480', '99', 'C3720', 'Cl', 0, '', '', '', '', '', 99, 1, 'C');

INSERT INTO equipexam
  (equipno, equipcode, examcode, examname, resprec, reflow, refhigh, paniclow, panichigh, deltavalue, seqno, examflag, examtype)
VALUES
  ('AU480', '05', 'L110481', 'T-Bil', 2, '', '', '', '', '', 5, 1, 'C');

INSERT INTO equipexam
  (equipno, equipcode, examcode, examname, resprec, reflow, refhigh, paniclow, panichigh, deltavalue, seqno, examflag, examtype)
VALUES
  ('KX21', '3', 'b1010', 'HGB', 1, '', '', '', '', '', 3, 1, 'H');

INSERT INTO equipexam
  (equipno, equipcode, examcode, examname, resprec, reflow, refhigh, paniclow, panichigh, deltavalue, seqno, examflag, examtype)
VALUES
  ('AU480', '06', 'L110480', 'D-Bil', 2, '', '', '', '', '', 6, 1, 'C');

INSERT INTO equipexam
  (equipno, equipcode, examcode, examname, resprec, reflow, refhigh, paniclow, panichigh, deltavalue, seqno, examflag, examtype)
VALUES
  ('AU480', '07', 'L110490', 'I-Bil', 2, '', '', '', '', '', 7, 1, 'C');

INSERT INTO equipexam
  (equipno, equipcode, examcode, examname, resprec, reflow, refhigh, paniclow, panichigh, deltavalue, seqno, examflag, examtype)
VALUES
  ('KX21', '2', 'RBC', 'RBC', 2, '', '', '', '', '', 2, 1, 'H');

INSERT INTO equipexam
  (equipno, equipcode, examcode, examname, resprec, reflow, refhigh, paniclow, panichigh, deltavalue, seqno, examflag, examtype)
VALUES
  ('KX21', '1', 'b1050', 'WBC', 1, '', '', '', '', '', 1, 1, 'H');

INSERT INTO equipexam
  (equipno, equipcode, examcode, examname, resprec, reflow, refhigh, paniclow, panichigh, deltavalue, seqno, examflag, examtype)
VALUES
  ('AU480', '10', 'L110300', 'ALP', 0, '', '', '', '', '', 10, 1, 'C');

INSERT INTO equipexam
  (equipno, equipcode, examcode, examname, resprec, reflow, refhigh, paniclow, panichigh, deltavalue, seqno, examflag, examtype)
VALUES
  ('AU480', '11', 'L110290', 'LDH', 0, '', '', '', '', '', 11, 1, 'C');

INSERT INTO equipexam
  (equipno, equipcode, examcode, examname, resprec, reflow, refhigh, paniclow, panichigh, deltavalue, seqno, examflag, examtype)
VALUES
  ('AU480', '13', 'L010103', 'BUN', 1, '', '', '', '', '', 13, 1, 'C');

INSERT INTO equipexam
  (equipno, equipcode, examcode, examname, resprec, reflow, refhigh, paniclow, panichigh, deltavalue, seqno, examflag, examtype)
VALUES
  ('KX21', '10', 'MXD%', 'MXD%', 1, '', '', '', '', '', 10, 1, 'H');

INSERT INTO equipexam
  (equipno, equipcode, examcode, examname, resprec, reflow, refhigh, paniclow, panichigh, deltavalue, seqno, examflag, examtype)
VALUES
  ('AU480', '15', 'L11050501', 'B/C', 1, '', '', '', '', '', 15, 1, 'C');

INSERT INTO equipexam
  (equipno, equipcode, examcode, examname, resprec, reflow, refhigh, paniclow, panichigh, deltavalue, seqno, examflag, examtype)
VALUES
  ('AU480', '16', 'L110165', 'chol', 0, '', '', '', '', '', 16, 1, 'C');

INSERT INTO equipexam
  (equipno, equipcode, examcode, examname, resprec, reflow, refhigh, paniclow, panichigh, deltavalue, seqno, examflag, examtype)
VALUES
  ('AU480', '18', 'L11019501', 'VLDL', 0, '', '', '', '', '', 18, 1, 'C');

INSERT INTO equipexam
  (equipno, equipcode, examcode, examname, resprec, reflow, refhigh, paniclow, panichigh, deltavalue, seqno, examflag, examtype)
VALUES
  ('AU480', '21', 'L11017501', 'CRF', 1, '', '', '', '', '', 21, 1, 'C');

INSERT INTO equipexam
  (equipno, equipcode, examcode, examname, resprec, reflow, refhigh, paniclow, panichigh, deltavalue, seqno, examflag, examtype)
VALUES
  ('AU480', '23', 'L010108', 'Ca', 1, '', '', '', '', '', 23, 1, 'C');

INSERT INTO equipexam
  (equipno, equipcode, examcode, examname, resprec, reflow, refhigh, paniclow, panichigh, deltavalue, seqno, examflag, examtype)
VALUES
  ('AU480', '24', 'L110545', 'I.P', 1, '', '', '', '', '', 24, 1, 'C');

INSERT INTO equipexam
  (equipno, equipcode, examcode, examname, resprec, reflow, refhigh, paniclow, panichigh, deltavalue, seqno, examflag, examtype)
VALUES
  ('AU480', '25', 'L110520', 'U.A', 1, '', '', '', '', '', 25, 1, 'C');

INSERT INTO equipexam
  (equipno, equipcode, examcode, examname, resprec, reflow, refhigh, paniclow, panichigh, deltavalue, seqno, examflag, examtype)
VALUES
  ('AU480', '26', 'L110306', 'Amyl', 0, '', '', '', '', '', 26, 1, 'C');

INSERT INTO equipexam
  (equipno, equipcode, examcode, examname, resprec, reflow, refhigh, paniclow, panichigh, deltavalue, seqno, examflag, examtype)
VALUES
  ('AU480', '27', 'L110040', 'CRP', 2, '', '', '', '', '', 27, 1, 'C');

INSERT INTO equipexam
  (equipno, equipcode, examcode, examname, resprec, reflow, refhigh, paniclow, panichigh, deltavalue, seqno, examflag, examtype)
VALUES
  ('AU480', '28', 'L110907', 'CPK', 0, '', '', '', '', '', 28, 1, 'C');

INSERT INTO equipexam
  (equipno, equipcode, examcode, examname, resprec, reflow, refhigh, paniclow, panichigh, deltavalue, seqno, examflag, examtype)
VALUES
  ('AU480', '29', 'L110325', 'CKMB', 1, '', '', '', '', '', 29, 1, 'C');

INSERT INTO equipexam
  (equipno, equipcode, examcode, examname, resprec, reflow, refhigh, paniclow, panichigh, deltavalue, seqno, examflag, examtype)
VALUES
  ('AU480', '30', 'L110240', 'TIBC', 1, '', '', '', '', '', 30, 1, 'C');

INSERT INTO equipexam
  (equipno, equipcode, examcode, examname, resprec, reflow, refhigh, paniclow, panichigh, deltavalue, seqno, examflag, examtype)
VALUES
  ('AU480', '31', 'L110251', 'Ferr', 1, '', '', '', '', '', 31, 1, 'C');

INSERT INTO equipexam
  (equipno, equipcode, examcode, examname, resprec, reflow, refhigh, paniclow, panichigh, deltavalue, seqno, examflag, examtype)
VALUES
  ('AU480', '32', 'L110235', 'Fe', 1, '', '', '', '', '', 32, 1, 'C');

INSERT INTO equipexam
  (equipno, equipcode, examcode, examname, resprec, reflow, refhigh, paniclow, panichigh, deltavalue, seqno, examflag, examtype)
VALUES
  ('AU480', '33', 'L110245', 'UIBC', 1, '', '', '', '', '', 33, 1, 'C');

INSERT INTO equipexam
  (equipno, equipcode, examcode, examname, resprec, reflow, refhigh, paniclow, panichigh, deltavalue, seqno, examflag, examtype)
VALUES
  ('KX21', '15', 'RDW', 'RDW', 1, '', '', '', '', '', 15, 1, 'H');

INSERT INTO equipexam
  (equipno, equipcode, examcode, examname, resprec, reflow, refhigh, paniclow, panichigh, deltavalue, seqno, examflag, examtype)
VALUES
  ('KX21', '16', 'PDW', 'PDW', 1, '', '', '', '', '', 16, 1, 'H');

INSERT INTO equipexam
  (equipno, equipcode, examcode, examname, resprec, reflow, refhigh, paniclow, panichigh, deltavalue, seqno, examflag, examtype)
VALUES
  ('KX21', '17', 'MPV', 'MPV', 1, '', '', '', '', '', 17, 1, 'H');

INSERT INTO equipexam
  (equipno, equipcode, examcode, examname, resprec, reflow, refhigh, paniclow, panichigh, deltavalue, seqno, examflag, examtype)
VALUES
  ('AU480', '08', 'B2570', 'AST', 0, '', '', '', '', '', 8, 1, 'C');

INSERT INTO equipexam
  (equipno, equipcode, examcode, examname, resprec, reflow, refhigh, paniclow, panichigh, deltavalue, seqno, examflag, examtype)
VALUES
  ('KX21', '4', 'b1020', 'HCT', 1, '', '', '', '', '', 4, 1, 'H');

INSERT INTO equipexam
  (equipno, equipcode, examcode, examname, resprec, reflow, refhigh, paniclow, panichigh, deltavalue, seqno, examflag, examtype)
VALUES
  ('AU480', '19', 'hdl', 'HDL-C', 0, '', '', '', '', '', 19, 1, 'C');

INSERT INTO equipexam
  (equipno, equipcode, examcode, examname, resprec, reflow, refhigh, paniclow, panichigh, deltavalue, seqno, examflag, examtype)
VALUES
  ('AU480', '17', 'tg', 'T.G', 0, '', '', '', '', '', 17, 1, 'C');

INSERT INTO equipexam
  (equipno, equipcode, examcode, examname, resprec, reflow, refhigh, paniclow, panichigh, deltavalue, seqno, examflag, examtype)
VALUES
  ('AU480', '01', 'b00304', 'T.P', 1, '', '', '', '', '', 1, 1, 'C');

INSERT INTO equipexam
  (equipno, equipcode, examcode, examname, resprec, reflow, refhigh, paniclow, panichigh, deltavalue, seqno, examflag, examtype)
VALUES
  ('AU480', '14', 'cr', 'Creat', 2, '', '', '', '', '', 14, 1, 'C');

INSERT INTO equipexam
  (equipno, equipcode, examcode, examname, resprec, reflow, refhigh, paniclow, panichigh, deltavalue, seqno, examflag, examtype)
VALUES
  ('AU480', '20', 'c2430', 'LDL', 0, '', '', '', '', '', 19, 1, 'C');

INSERT INTO equipexam
  (equipno, equipcode, examcode, examname, resprec, reflow, refhigh, paniclow, panichigh, deltavalue, seqno, examflag, examtype)
VALUES
  ('AU480', '12', 'gtp', 'r-GTP', 0, '', '', '', '', '', 12, 1, 'C');

INSERT INTO equipexam
  (equipno, equipcode, examcode, examname, resprec, reflow, refhigh, paniclow, panichigh, deltavalue, seqno, examflag, examtype)
VALUES
  ('AU480', '22', 'f', 'GLU', 0, '', '', '', '', '', 22, 1, 'C');

INSERT INTO equipexam
  (equipno, equipcode, examcode, examname, resprec, reflow, refhigh, paniclow, panichigh, deltavalue, seqno, examflag, examtype)
VALUES
  ('KX21', '6', 'mch', 'MCH', 1, '', '', '', '', '', 6, 1, 'H');

INSERT INTO equipexam
  (equipno, equipcode, examcode, examname, resprec, reflow, refhigh, paniclow, panichigh, deltavalue, seqno, examflag, examtype)
VALUES
  ('KX21', '9', 'b10902', 'LYM%', 1, '', '', '', '', '', 9, 1, 'H');

INSERT INTO equipexam
  (equipno, equipcode, examcode, examname, resprec, reflow, refhigh, paniclow, panichigh, deltavalue, seqno, examflag, examtype)
VALUES
  ('KX21', '10', 'b10903', 'MXD%', 1, '', '', '', '', '', 10, 1, 'H');

INSERT INTO equipexam
  (equipno, equipcode, examcode, examname, resprec, reflow, refhigh, paniclow, panichigh, deltavalue, seqno, examflag, examtype)
VALUES
  ('KX21', '11', 'b10901', 'NEUT%', 1, '', '', '', '', '', 11, 1, 'H');

INSERT INTO equipexam
  (equipno, equipcode, examcode, examname, resprec, reflow, refhigh, paniclow, panichigh, deltavalue, seqno, examflag, examtype)
VALUES
  ('AU480', '09', 'b2580', 'ALT', 0, '', '', '', '', '', 9, 1, 'C');

INSERT INTO equipexam
  (equipno, equipcode, examcode, examname, resprec, reflow, refhigh, paniclow, panichigh, deltavalue, seqno, examflag, examtype)
VALUES
  ('KX21', '8', 'b1060', 'PLT', 0, '', '', '', '', '', 8, 1, 'H');

INSERT INTO equipexam
  (equipno, equipcode, examcode, examname, resprec, reflow, refhigh, paniclow, panichigh, deltavalue, seqno, examflag, examtype)
VALUES
  ('KX21', '5', 'mcv', 'MCV', 1, '', '', '', '', '', 5, 1, 'H');

INSERT INTO equipexam
  (equipno, equipcode, examcode, examname, resprec, reflow, refhigh, paniclow, panichigh, deltavalue, seqno, examflag, examtype)
VALUES
  ('KX21', '7', 'mchc', 'MCHC', 1, '', '', '', '', '', 7, 1, 'H');

