VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "clsResults"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit
    
Public OrdDt        As String
Public SpcNm        As String
Public TestNm       As String
Public VfyDt        As String
Public VfyId        As String
Public RstCd        As String
Public RstUnit      As String
Public HLDiv        As String
Public DPDiv        As String
Public RefRng       As String
Public TxtFg        As String
Public SenFg        As String
Public FootNoteFg   As String
Public RmkCd        As String
Public DcFg         As String
Public WorkArea     As String
Public AccDt        As String
Public AccSeq       As String
Public LastRst      As String
Public TestCd       As String
Public SpcCd        As String
Public TestDiv      As String
Public OrdDate      As String
Public SpcName      As String
Public DetailFg     As String
Public RstDiv       As String
Public MfyFg        As String
Public StsCd        As String
Public RcvDtTm      As String
Public VfyDtTm      As String
Public ColDtTm      As String
Public PtSex        As String
Public AgeDay       As String
Public AntiCd       As String
Public AntiNm       As String
Public SenRstBuf    As String

Public ClinicalNotice As String

Public Sub GetText()

End Sub
