/*########################
# Client Proxy Procedure Code
# generated by rpcmake version 5.1
# (compatible with stubs that generated by rpcmake version 2.0
#  compatible with stubs that generated by rpcmake version 3.0
#  compatible with stubs that generated by rpcmake version 3.5
#  compatible with stubs that generated by rpcmake version 4.3)
# on Monday, July 29, 19119 at 15:49:04
# 
# interface: smi_p_021 
# */

#include <stdio.h>
#if defined __mpexl || defined _MACINTOSH_
#include "dceinc.h"
#else
#include <dceinc.h>
#endif

long smi_p_021_POCT_insert_order(char *sz_iEQUIP_CD,
	char *sz_iPT_NO,
	char *sz_iTEST_DTETM,
	char *sz_iORD_SITE,
	char *sz_iORDCD,
	char *sz_iEDIT_ID,
	char *sz_iRESULT,
	char **msg)
{
/*  ODECOMMENT BEGIN DECLARATIONS smi_p_021 smi_p_021_POCT_insert_order */
	long rv = 0;	int Socket;
	struct table *dce_table = NULL;

/*  ODECOMMENT END DECLARATIONS smi_p_021 smi_p_021_POCT_insert_order */

	dce_checkver(2, 0);
	if ((Socket = dce_findserver("smi_p_021")) >= 0) {
/*  ODECOMMENT BEGIN MARSHALLING smi_p_021 smi_p_021_POCT_insert_order */
		dce_push_char_Nstr(Socket,"sz_iEQUIP_CD",sz_iEQUIP_CD);
		dce_push_char_Nstr(Socket,"sz_iPT_NO",sz_iPT_NO);
		dce_push_char_Nstr(Socket,"sz_iTEST_DTETM",sz_iTEST_DTETM);
		dce_push_char_Nstr(Socket,"sz_iORD_SITE",sz_iORD_SITE);
		dce_push_char_Nstr(Socket,"sz_iORDCD",sz_iORDCD);
		dce_push_char_Nstr(Socket,"sz_iEDIT_ID",sz_iEDIT_ID);
		dce_push_char_Nstr(Socket,"sz_iRESULT",sz_iRESULT);
/*  ODECOMMENT END MARSHALLING smi_p_021 smi_p_021_POCT_insert_order */
		dce_table = dce_submit("smi_p_021", "smi_p_021_POCT_insert_order", Socket);
	}
/*  ODECOMMENT BEGIN UNMARSHALLING smi_p_021 smi_p_021_POCT_insert_order */
	rv = dce_pop_long(dce_table,"dce_result");
	*msg = dce_pop_char_Nstr(dce_table,"msg");
/*  ODECOMMENT END UNMARSHALLING smi_p_021 smi_p_021_POCT_insert_order */
	dce_table_destroy(dce_table);
	return(rv);
}

long smi_p_021_POCT_order_DC(char *sz_iEQUIP_CD,
	char *sz_iPT_NO,
	char *sz_iTEST_DTETM,
	char **msg)
{
/*  ODECOMMENT BEGIN DECLARATIONS smi_p_021 smi_p_021_POCT_order_DC */
	long rv = 0;	int Socket;
	struct table *dce_table = NULL;

/*  ODECOMMENT END DECLARATIONS smi_p_021 smi_p_021_POCT_order_DC */

	dce_checkver(2, 0);
	if ((Socket = dce_findserver("smi_p_021")) >= 0) {
/*  ODECOMMENT BEGIN MARSHALLING smi_p_021 smi_p_021_POCT_order_DC */
		dce_push_char_Nstr(Socket,"sz_iEQUIP_CD",sz_iEQUIP_CD);
		dce_push_char_Nstr(Socket,"sz_iPT_NO",sz_iPT_NO);
		dce_push_char_Nstr(Socket,"sz_iTEST_DTETM",sz_iTEST_DTETM);
/*  ODECOMMENT END MARSHALLING smi_p_021 smi_p_021_POCT_order_DC */
		dce_table = dce_submit("smi_p_021", "smi_p_021_POCT_order_DC", Socket);
	}
/*  ODECOMMENT BEGIN UNMARSHALLING smi_p_021 smi_p_021_POCT_order_DC */
	rv = dce_pop_long(dce_table,"dce_result");
	*msg = dce_pop_char_Nstr(dce_table,"msg");
/*  ODECOMMENT END UNMARSHALLING smi_p_021 smi_p_021_POCT_order_DC */
	dce_table_destroy(dce_table);
	return(rv);
}

long smi_p_021_update_ptno(char *sz_iEQUIP_CD,
	char *sz_iTEST_DTETM,
	char *sz_iNEW_PT_NO,
	char **msg)
{
/*  ODECOMMENT BEGIN DECLARATIONS smi_p_021 smi_p_021_update_ptno */
	long rv = 0;	int Socket;
	struct table *dce_table = NULL;

/*  ODECOMMENT END DECLARATIONS smi_p_021 smi_p_021_update_ptno */

	dce_checkver(2, 0);
	if ((Socket = dce_findserver("smi_p_021")) >= 0) {
/*  ODECOMMENT BEGIN MARSHALLING smi_p_021 smi_p_021_update_ptno */
		dce_push_char_Nstr(Socket,"sz_iEQUIP_CD",sz_iEQUIP_CD);
		dce_push_char_Nstr(Socket,"sz_iTEST_DTETM",sz_iTEST_DTETM);
		dce_push_char_Nstr(Socket,"sz_iNEW_PT_NO",sz_iNEW_PT_NO);
/*  ODECOMMENT END MARSHALLING smi_p_021 smi_p_021_update_ptno */
		dce_table = dce_submit("smi_p_021", "smi_p_021_update_ptno", Socket);
	}
/*  ODECOMMENT BEGIN UNMARSHALLING smi_p_021 smi_p_021_update_ptno */
	rv = dce_pop_long(dce_table,"dce_result");
	*msg = dce_pop_char_Nstr(dce_table,"msg");
/*  ODECOMMENT END UNMARSHALLING smi_p_021 smi_p_021_update_ptno */
	dce_table_destroy(dce_table);
	return(rv);
}

long smi_p_021_POCT_insert_order_set(char *sz_iEQUIP_CD,
	char *sz_iPT_NO,
	char *sz_iTEST_DTETM,
	char *sz_iORD_SITE,
	char *sz_iORDCD,
	char *sz_iEDIT_ID,
	long i_RSLT_CNT,
	char **sz_iRSLT_CDS,
	char **sz_iRESULTS,
	char **msg)
{
/*  ODECOMMENT BEGIN DECLARATIONS smi_p_021 smi_p_021_POCT_insert_order_set */
	long rv = 0;	int Socket;
	struct table *dce_table = NULL;

/*  ODECOMMENT END DECLARATIONS smi_p_021 smi_p_021_POCT_insert_order_set */

	dce_checkver(2, 0);
	if ((Socket = dce_findserver("smi_p_021")) >= 0) {
/*  ODECOMMENT BEGIN MARSHALLING smi_p_021 smi_p_021_POCT_insert_order_set */
		dce_push_char_Nstr(Socket,"sz_iEQUIP_CD",sz_iEQUIP_CD);
		dce_push_char_Nstr(Socket,"sz_iPT_NO",sz_iPT_NO);
		dce_push_char_Nstr(Socket,"sz_iTEST_DTETM",sz_iTEST_DTETM);
		dce_push_char_Nstr(Socket,"sz_iORD_SITE",sz_iORD_SITE);
		dce_push_char_Nstr(Socket,"sz_iORDCD",sz_iORDCD);
		dce_push_char_Nstr(Socket,"sz_iEDIT_ID",sz_iEDIT_ID);
		dce_push_long(Socket,"i_RSLT_CNT",i_RSLT_CNT);
		dce_push_char_Narr(Socket,"sz_iRSLT_CDS",
			sz_iRSLT_CDS);
		dce_push_char_Narr(Socket,"sz_iRESULTS",
			sz_iRESULTS);
/*  ODECOMMENT END MARSHALLING smi_p_021 smi_p_021_POCT_insert_order_set */
		dce_table = dce_submit("smi_p_021", "smi_p_021_POCT_insert_order_set", Socket);
	}
/*  ODECOMMENT BEGIN UNMARSHALLING smi_p_021 smi_p_021_POCT_insert_order_set */
	rv = dce_pop_long(dce_table,"dce_result");
	*msg = dce_pop_char_Nstr(dce_table,"msg");
/*  ODECOMMENT END UNMARSHALLING smi_p_021 smi_p_021_POCT_insert_order_set */
	dce_table_destroy(dce_table);
	return(rv);
}

